### ISSUE TITLE
Symbolic expressions in argument annotations

### ISSUE THREAD

**Issue by Rick-McCoy** [google/jaxtyping#148]
This results in an error:

```python
import torch
from torch import nn, Tensor
from torch.nn import functional as F
from jaxtyping import Float

class GGELU(nn.Module):
    def forward(self, x: Float[Tensor, "batch d"]) -> Float[Tensor, "batch d//2"]:
        y, gate = x.chunk(2, dim=-1)
        return F.gelu(gate) * y

print(GGELU()(torch.randn(24).reshape(4, 6)).shape)

--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/<snip>/.venv/lib/python3.11/site-packages/jaxtyping/_array_types.py", line 122, in _check_dims
    eval_size = eval(cls_dim.expr, single_memo.copy())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'd' is not defined. Did you mean: 'id'?
```

This does not:

```python
import torch
from torch import nn, Tensor
from torch.nn import functional as F
from jaxtyping import Float

class GGELU(nn.Module):
    def forward(self, x: Float[Tensor, "batch d"]) -> Float[Tensor, "batch d"]:
        y, gate = x.chunk(2, dim=-1)
        return F.gelu(gate) * y

print(GGELU()(torch.randn(24).reshape(4, 6)).shape)

--------------------------------------------------------------------------
torch.Size([4, 3])
```

Despite the `d` dimension size changing between the input and output, no error is raised.
I would expect the first example to work, and the second to fail, but it is the other way around.
Am I missing something?

**Comment by patrick-kidger** [comment]
From your examples, it looks like you're using an import hook to add runtime type checking (whether that's typeguard or beartype), but not to add the `jaxtyping.jaxtyped` decorator.

Try using jaxtyping's import hook to add both at the same time.

**Comment by Rick-McCoy** [comment]
Yeah, it turns out I was only using `beartype_this_package()`. Should I add the `jaxtyped` decorator to every function I'm type checking? `beartype_this_package` was convenient in that I only needed to add it to `__init__.py`.

**Comment by Rick-McCoy** [comment]
Works fine. Closing issue!
